### ISSUE TITLE
CompressionError: bz2 module is not available

### ISSUE THREAD

**Issue by brenthmiras** [edx/xblock-sdk#61]
I'm running ubuntu 12.10. I cloned this repo, and ran make install. The build always fails with this message:     raise CompressionError("bz2 module is not available")
CompressionError: bz2 module is not available

Storing complete log in /home/codemagnus/.pip/pip.log
make: **\* [pip] Error 2

**Comment by nedbat** [comment]
It sounds like you built your own Python? Or somehow you don't have the bz libraries available.

**Comment by radzhome** [comment]
On centos - yum install bzip2 bzip2-devel

then re-compile it again
