### ISSUE TITLE
Issue with deploying xblock created with this sdk.

### ISSUE THREAD

**Issue by 3nabhs** [edx/xblock-sdk#67]
Hey,
I have weird problem with XBlock, that I've created using this sdk. I've started with making new block using script startnew.py. When I was finished with it, I made sure it works as it should, and It did work just fine in workbench provided by this SDK. Now, you can't check how studio mode looks like in workbench (at least I do not know how) so I decided to test it on my working edx-platform (devstack). It installed perfectly fine, no errors of note. The thing is, it doesn't show in the studio on "advanced problems" tab. I've tried to check if it's maybe my platform instance that's at fault here, but other XBlocks taken from internet work as they should be. 

Now, my question is, are there any limits on XBlocks to work on studio workbench, like maybe it cannot be too large, or you cannot use some functions in it. My XBlock basically works on iframe and it's communicating with other site back and forth. Maybe that's the problem? 

That's what I get when installing on my platform:

```
The directory '/home/vagrant/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
You are using pip version 6.0.8, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Processing /edx/app/edxapp/edx-platform/cppcompiler
Requirement already satisfied (use --upgrade to upgrade): XBlock in /edx/app/edxapp/venvs/edxapp/src/xblock (from cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): lxml in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): pytz in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): webob in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->cpp==0.1)
Requirement already satisfied (use --upgrade to upgrade): six in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from python-dateutil->XBlock->cpp==0.1)
Installing collected packages: cpp
  Running setup.py install for cpp
Successfully installed cpp-0.1
```

I get the same permission error when I install other XBlocks and they are not the problem it seems.
I've also tried to make studio view with StudioEditableXBlockMixin from xblock-utils but it didn't change anything. 

Also, keep in mind, I'm pretty new to python so it may be that I've made some mistakes in code, but the thing is, it does work in xblock-sdk workbench, so i think it should work just fine in studio, shouldn't it?

**Comment by tusbar** [comment]
It looks like your installing the XBlock, connected as the default `vagrant` user.

You should install it in `edxapp`’s virtual env by doing the following:

```shell
$ vagrant ssh
$ sudo su edxapp
$ pip install -e git+https://github.com/your/xblock.git#egg=xblock-name
```

Then you should restart studio and you should be good to go.

**Comment by 3nabhs** [comment]
hmm, I've installed my Xblock on default user, but with:

 ```  vagrant@precise64:~$ sudo -u edxapp /edx/bin/pip.edxapp install /path/to/your/block```

So I assumed it installs it on edxapp user. It did work for other blocks though. Now, I've installed it as you suggested, and it still doesn't show up in advanced modules. What I did was uninstall previous tries, reload vagrant instance, install XBlock in edxapp user, reload vagrant, and then run studio. Still no effect. 

Is it possible, that somehow my studio_view function is at fault? What I mean is, is it possible that errors  in my studio_view function make it so XBlock doesn't show up in advanced modules, but it does work in workbench since it basically shows only user_view?

**Comment by stvstnfrd** [comment]
@natabene Given the age and info in this issue, can we close it out?
Also, not sure if you're the right person to ping; figured I'd start there though :)

**Comment by natabene** [comment]
@stvstnfrd Looks like our bot is not covering this repo at all (@nedbat should we change to bot to scan this repo?). We can either have someone give it a quick looks, or just close it if you think it is too old by now to be of any benefit.

**Comment by nedbat** [comment]
@natabene the bot now watches all repos in the edx organization. But this is an issue, not a pull request, and so would be ignored anyway.  I will close it.
