### ISSUE TITLE
XBlockAsides generate warnings and extra info when following tutorial

### ISSUE THREAD

**Issue by jmatsushita** [edx/xblock-sdk#73]
Hi,

I'm writing my first XBlock and ran into this FutureWarning on the console when running the sdk.

```
Development server is running at http://x.x.x.x:18000/
Quit the server with CONTROL-C.
/opt/xblock_development/venv/src/xblock/xblock/runtime.py:578: FutureWarning: IdGenerator will be required in the future in order to support XBlockAsides
  warnings.warn("IdGenerator will be required in the future in order to support XBlockAsides", FutureWarning)
[14/Oct/2015 11:35:04] "GET / HTTP/1.1" 200 1796
```

And then when accessing it, I get a lot of Aside related UI components.

![image](https://cloud.githubusercontent.com/assets/356097/10488967/6df483f2-729b-11e5-858c-f15444dace04.png)

Cheers!

Jun

**Comment by jmatsushita** [comment]
Workaround for the second problem is to ```pip uninstall acid-xblock```. Thanks @nedbat

**Comment by nedbat** [comment]
This should now be fixed.
