### ISSUE TITLE
Fail to runserver

### ISSUE THREAD

**Issue by mityakoval** [edx/xblock-sdk#86]
Fail to run `python xblock-sdk/manage.py runserver' 

Error:

`Traceback (most recent call last):`
 `File "xblock-sdk/manage.py", line 10, in <module>`
`execute_from_command_line(sys.argv)`
`File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 351, in execute_from_command_line`
`utility.execute()`
`File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)`
`File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 177, in fetch_command`
`commands = get_commands()`
`File "/usr/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper`
`result = user_function(*args, **kwds)`
`File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 72, in get_commands`
`for app_config in reversed(list(apps.get_app_configs())):`
`File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()`
`File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")`
`django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`

**Comment by stvstnfrd** [comment]
@natabene Given the age and info here, should we close this out?

**Comment by natabene** [comment]
@stvstnfrd Hm, I didn't even know this PR existed. Looks like bot didn't create a ticket for it and we didn't review it all. Would you like someone from engineering to take a look or do you prefer to close it?

**Comment by stvstnfrd** [comment]
I'd politely prefer to close it :)
