### ISSUE TITLE
Wird problem with scopes.

### ISSUE THREAD

**Issue by 3nabhs** [edx/xblock-sdk#87]
Hey,
I do not know if that's the correct place to ask this questions, but But those are the problems I've run into when developing my own xblock. 
There's weird interaction with fields in my xblock and Devstack studio. I'm not sure it this happens on fullstack.
When I set scope: user_state in one of my fields, it's shared between all the instances of the my xblock, but only within the same subsection in studio/lms of the course. When there's only one xblock per subsection there's no problem at all.
Shouldn't it be saved only within specific xblock instance? Or It does work as it should, and if so, what scope should I use, to save answer form the exercise that is in my xblock?

**Comment by stvstnfrd** [comment]
@natabene Given the age and info here, should we close this out?

**Comment by natabene** [comment]
@stvstnfrd We can either have someone give a brief look, or if you think it is hopeless due to age by now, I can close. Let me know.

**Comment by stvstnfrd** [comment]
@natabene Yes, that was my polite way of suggesting this ticket is too old and lacks enough information to be actionable :)
